### ISSUE TITLE
Use *.sublime-syntax files

### ISSUE THREAD

**Issue by jrappen** [ihodev/sublime-file-icons#66]
Replace the `*.tmLanguage` files with `*.sublime-syntax` files as this is ST3 only anyway.

Example structure:

```yml
%YAML 1.2
---
# http://www.sublimetext.com/docs/3/syntax.html
name: JSON (Sublime)
file_extensions:
  - .no-sublime-package
  - sublime-commands
  - sublime-menu
  - sublime-project
  - sublime-settings
  - sublime-theme
  - sublime-workspace
scope: source.json.sublime
contexts:
  main:
    - include: scope:source.json
```
